# The standard Draw-A-Man checklist criteria (48 items)
# Source: web/index.html / labels spreadsheet
CRITERIA = [
    "Legs", 
    "Arms", 
    "Trunk", 
    "Length of trunk greater than breadth",
    "Shoulders are indicated (abrupt broadening of trunk below neck)",
    "Both arms and legs are attached (reasonably) to the trunk",
    "Arms and legs attached (reasonably) to trunk at correct points",
    "Neck present",
    "Outline of the neck is continuous with that of the head, trunk, or both",
    "Eyes present (one or two)", 
    "Nose", 
    "Mouth",
    "Nose and mouth in two dimensions, two lips shown", 
    "Nostril shown",
    "Hair shown", 
    "Hair better than a scribble and covering the scalp",
    "Teeth", 
    "Tongue", 
    "Arm joint shown – elbow, shoulder, or both",
    "Leg joint shown – knee, hip, or both",
    "Ears present (Two ears in full face, one ear in side profile view)",
    "Ears present in correct position and proportion",
    "Eye details – brow or lashes shown", 
    "Eye detail – pupil shown",
    "Eye detail – proportion. Length greater than width", 
    "Smile", 
    "Belly button",
    "Clothing present (any clear representation of clothing)",
    "Two articles of clothing non transparent (e.g., hat, trousers)",
    "Entire drawing free from transparencies",
    "Four articles of clothing definitely indicated (e.g., hat, shoes, coat)",
    "Fingers present (any indication)", 
    "Correct number of fingers shown",
    "Fingers in two dimensions – length greater than breadth",
    "Opposition of thumb clearly defined", 
    "Hand shown distinct from fingers and arm",
    "Fingernail(s)", 
    "Head not more than 1/2 or less than 1/10 of trunk",
    "Arm length is equal to the trunk length but not reaching the knees",
    "Legs length more than trunk length, but less than 2x trunk width",
    "Feet in two dimensions – not more than 1/3 or less than 1/10 of leg",
    "Both arms and legs in two dimensions",
    "Lines firm without marked tendency to cross, gap, or overlap",
    "All lines firm with correct joining",
    "Outline of head without obvious irregularities",
    "Trunk outline without obvious irregularities",
    "Arms and legs without irregularities (2D, no narrowing at junction)",
    "Paired body parts are symmetrical"
]

# Supported image extensions (from scripts)
IMG_EXTS = {
    ".jpg",
    ".jpeg",
    ".png",
    ".bmp",
    ".webp",
    ".tif",
    ".tiff",
}